# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zhangs\Documents\Qt_Projects\Python\MyProject\Spec2.0\myui\AppearanceDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppearanceDialog(object):
    def setupUi(self, AppearanceDialog):
        AppearanceDialog.setObjectName("AppearanceDialog")
        AppearanceDialog.resize(255, 175)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AppearanceDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setObjectName("formLayout")
        self.tabWidget = QtWidgets.QTabWidget(AppearanceDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTheme = QtWidgets.QWidget()
        self.tabTheme.setObjectName("tabTheme")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabTheme)
        self.verticalLayout.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tabTheme)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBox)
        self.fontComboBox.setObjectName("fontComboBox")
        self.gridLayout_3.addWidget(self.fontComboBox, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout.setStretch(0, 4)
        self.tabWidget.addTab(self.tabTheme, "")
        self.tabDataFormat = QtWidgets.QWidget()
        self.tabDataFormat.setObjectName("tabDataFormat")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabDataFormat)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabDataFormat)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tabDataFormat, "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tabWidget)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AppearanceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(AppearanceDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AppearanceDialog)

    def retranslateUi(self, AppearanceDialog):
        _translate = QtCore.QCoreApplication.translate
        AppearanceDialog.setWindowTitle(_translate("AppearanceDialog", "Dialog"))
        self.groupBox.setTitle(_translate("AppearanceDialog", "Custom"))
        self.comboBox.setItemText(0, _translate("AppearanceDialog", "Windows"))
        self.comboBox.setItemText(1, _translate("AppearanceDialog", "Vista"))
        self.comboBox.setItemText(2, _translate("AppearanceDialog", "Fusion"))
        self.label_3.setText(_translate("AppearanceDialog", "Front"))
        self.label_2.setText(_translate("AppearanceDialog", "Color"))
        self.checkBox.setText(_translate("AppearanceDialog", "WindowBoarder"))
        self.label.setText(_translate("AppearanceDialog", "Win Style"))
        self.comboBox_2.setItemText(0, _translate("AppearanceDialog", "Light"))
        self.comboBox_2.setItemText(1, _translate("AppearanceDialog", "Dark"))
        self.comboBox_2.setItemText(2, _translate("AppearanceDialog", "Twilight"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTheme), _translate("AppearanceDialog", "Custom"))
        self.groupBox_2.setTitle(_translate("AppearanceDialog", "Template"))
        self.pushButton_3.setText(_translate("AppearanceDialog", "PushButton"))
        self.pushButton_2.setText(_translate("AppearanceDialog", "PushButton"))
        self.pushButton.setText(_translate("AppearanceDialog", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDataFormat), _translate("AppearanceDialog", "Template"))
