# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zhangs\Documents\Qt_Projects\Python\MyProject\Spec2.0\myui\MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 449)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(419, 323))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serialLed = LedIndicator(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialLed.sizePolicy().hasHeightForWidth())
        self.serialLed.setSizePolicy(sizePolicy)
        self.serialLed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.serialLed.setText("")
        self.serialLed.setObjectName("serialLed")
        self.horizontalLayout.addWidget(self.serialLed)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setStyleSheet("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pbStart = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbStart.sizePolicy().hasHeightForWidth())
        self.pbStart.setSizePolicy(sizePolicy)
        self.pbStart.setMinimumSize(QtCore.QSize(40, 45))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.pbStart.setFont(font)
        self.pbStart.setAcceptDrops(False)
        self.pbStart.setStyleSheet("background-color: rgb(201, 201, 201);")
        self.pbStart.setFlat(False)
        self.pbStart.setObjectName("pbStart")
        self.gridLayout_10.addWidget(self.pbStart, 1, 0, 1, 1)
        self.pbStop = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbStop.sizePolicy().hasHeightForWidth())
        self.pbStop.setSizePolicy(sizePolicy)
        self.pbStop.setMinimumSize(QtCore.QSize(40, 45))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.pbStop.setFont(font)
        self.pbStop.setStyleSheet("background-color: rgb(201, 201, 201);")
        self.pbStop.setObjectName("pbStop")
        self.gridLayout_10.addWidget(self.pbStop, 1, 2, 1, 1)
        self.timeLCD = QtWidgets.QLCDNumber(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLCD.sizePolicy().hasHeightForWidth())
        self.timeLCD.setSizePolicy(sizePolicy)
        self.timeLCD.setMinimumSize(QtCore.QSize(60, 50))
        self.timeLCD.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.timeLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timeLCD.setObjectName("timeLCD")
        self.gridLayout_10.addWidget(self.timeLCD, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 3, 0, 1, 1)
        self.pbSnap = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSnap.sizePolicy().hasHeightForWidth())
        self.pbSnap.setSizePolicy(sizePolicy)
        self.pbSnap.setMinimumSize(QtCore.QSize(40, 45))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.pbSnap.setFont(font)
        self.pbSnap.setStyleSheet("background-color: rgb(201, 201, 201);")
        self.pbSnap.setFlat(False)
        self.pbSnap.setObjectName("pbSnap")
        self.gridLayout_10.addWidget(self.pbSnap, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 0, 0, 1, 1)
        self.modCB = QtWidgets.QComboBox(self.frame)
        self.modCB.setMinimumSize(QtCore.QSize(0, 35))
        self.modCB.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(237, 237, 237);")
        self.modCB.setObjectName("modCB")
        self.modCB.addItem("")
        self.modCB.addItem("")
        self.gridLayout_10.addWidget(self.modCB, 0, 1, 1, 2)
        self.gridLayout_2.addWidget(self.frame, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.measure = QtWidgets.QWidget()
        self.measure.setObjectName("measure")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.measure)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.packFlagPB = QtWidgets.QPushButton(self.measure)
        self.packFlagPB.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.packFlagPB.setFont(font)
        self.packFlagPB.setStyleSheet("")
        self.packFlagPB.setObjectName("packFlagPB")
        self.gridLayout_9.addWidget(self.packFlagPB, 0, 2, 1, 1)
        self.fdMaxLE = QtWidgets.QLineEdit(self.measure)
        self.fdMaxLE.setMinimumSize(QtCore.QSize(0, 30))
        self.fdMaxLE.setAlignment(QtCore.Qt.AlignCenter)
        self.fdMaxLE.setObjectName("fdMaxLE")
        self.gridLayout_9.addWidget(self.fdMaxLE, 1, 1, 1, 1)
        self.setTimePB = QtWidgets.QPushButton(self.measure)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.setTimePB.setFont(font)
        self.setTimePB.setObjectName("setTimePB")
        self.gridLayout_9.addWidget(self.setTimePB, 3, 2, 1, 1)
        self.packFlagLE = QtWidgets.QLineEdit(self.measure)
        self.packFlagLE.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(False)
        font.setWeight(50)
        self.packFlagLE.setFont(font)
        self.packFlagLE.setAlignment(QtCore.Qt.AlignCenter)
        self.packFlagLE.setObjectName("packFlagLE")
        self.gridLayout_9.addWidget(self.packFlagLE, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.measure)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_9.addWidget(self.line, 2, 1, 1, 2)
        self.fdMaxPB = QtWidgets.QPushButton(self.measure)
        self.fdMaxPB.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.fdMaxPB.setFont(font)
        self.fdMaxPB.setStyleSheet("")
        self.fdMaxPB.setObjectName("fdMaxPB")
        self.gridLayout_9.addWidget(self.fdMaxPB, 1, 2, 1, 1)
        self.setMaxEPB = QtWidgets.QPushButton(self.measure)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.setMaxEPB.setFont(font)
        self.setMaxEPB.setObjectName("setMaxEPB")
        self.gridLayout_9.addWidget(self.setMaxEPB, 5, 2, 1, 1)
        self.setRefNumPB = QtWidgets.QPushButton(self.measure)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.setRefNumPB.setFont(font)
        self.setRefNumPB.setObjectName("setRefNumPB")
        self.gridLayout_9.addWidget(self.setRefNumPB, 7, 2, 1, 1)
        self.setChPB = QtWidgets.QPushButton(self.measure)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.setChPB.setFont(font)
        self.setChPB.setObjectName("setChPB")
        self.gridLayout_9.addWidget(self.setChPB, 4, 2, 1, 1)
        self.measTimeLE = QtWidgets.QLineEdit(self.measure)
        self.measTimeLE.setMinimumSize(QtCore.QSize(0, 30))
        self.measTimeLE.setAlignment(QtCore.Qt.AlignCenter)
        self.measTimeLE.setObjectName("measTimeLE")
        self.gridLayout_9.addWidget(self.measTimeLE, 3, 1, 1, 1)
        self.chNumLE = QtWidgets.QLineEdit(self.measure)
        self.chNumLE.setMinimumSize(QtCore.QSize(0, 30))
        self.chNumLE.setAlignment(QtCore.Qt.AlignCenter)
        self.chNumLE.setObjectName("chNumLE")
        self.gridLayout_9.addWidget(self.chNumLE, 4, 1, 1, 1)
        self.maxELE = QtWidgets.QLineEdit(self.measure)
        self.maxELE.setMinimumSize(QtCore.QSize(0, 30))
        self.maxELE.setAlignment(QtCore.Qt.AlignCenter)
        self.maxELE.setObjectName("maxELE")
        self.gridLayout_9.addWidget(self.maxELE, 5, 1, 1, 1)
        self.refNumLE = QtWidgets.QLineEdit(self.measure)
        self.refNumLE.setMinimumSize(QtCore.QSize(0, 30))
        self.refNumLE.setAlignment(QtCore.Qt.AlignCenter)
        self.refNumLE.setObjectName("refNumLE")
        self.gridLayout_9.addWidget(self.refNumLE, 7, 1, 1, 1)
        self.tabWidget.addTab(self.measure, "")
        self.tabFit = QtWidgets.QWidget()
        self.tabFit.setObjectName("tabFit")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tabFit)
        self.gridLayout_11.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.dropFitType = QtWidgets.QComboBox(self.tabFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dropFitType.sizePolicy().hasHeightForWidth())
        self.dropFitType.setSizePolicy(sizePolicy)
        self.dropFitType.setMinimumSize(QtCore.QSize(60, 35))
        self.dropFitType.setObjectName("dropFitType")
        self.dropFitType.addItem("")
        self.dropFitType.addItem("")
        self.dropFitType.addItem("")
        self.dropFitType.addItem("")
        self.dropFitType.addItem("")
        self.gridLayout_11.addWidget(self.dropFitType, 0, 1, 1, 2)
        self.pbFitCurve = QtWidgets.QPushButton(self.tabFit)
        self.pbFitCurve.setMinimumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.pbFitCurve.setFont(font)
        self.pbFitCurve.setObjectName("pbFitCurve")
        self.gridLayout_11.addWidget(self.pbFitCurve, 4, 1, 1, 2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_6 = QtWidgets.QLabel(self.tabFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.dropMethod = QtWidgets.QComboBox(self.tabFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dropMethod.sizePolicy().hasHeightForWidth())
        self.dropMethod.setSizePolicy(sizePolicy)
        self.dropMethod.setMinimumSize(QtCore.QSize(60, 35))
        self.dropMethod.setObjectName("dropMethod")
        self.gridLayout_7.addWidget(self.dropMethod, 0, 1, 1, 2)
        self.tbEquation = QtWidgets.QTextBrowser(self.tabFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbEquation.sizePolicy().hasHeightForWidth())
        self.tbEquation.setSizePolicy(sizePolicy)
        self.tbEquation.setMinimumSize(QtCore.QSize(0, 40))
        self.tbEquation.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setBold(False)
        font.setWeight(50)
        self.tbEquation.setFont(font)
        self.tbEquation.setReadOnly(True)
        self.tbEquation.setObjectName("tbEquation")
        self.gridLayout_7.addWidget(self.tbEquation, 1, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tabFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 1, 0, 2, 1)
        self.caliEqCKB = QtWidgets.QCheckBox(self.tabFit)
        self.caliEqCKB.setEnabled(False)
        self.caliEqCKB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.caliEqCKB.setObjectName("caliEqCKB")
        self.gridLayout_7.addWidget(self.caliEqCKB, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_7, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tabFit, "")
        self.tabCali = QtWidgets.QWidget()
        self.tabCali.setObjectName("tabCali")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tabCali)
        self.gridLayout_12.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pbDel = QtWidgets.QPushButton(self.tabCali)
        self.pbDel.setMinimumSize(QtCore.QSize(0, 35))
        self.pbDel.setObjectName("pbDel")
        self.gridLayout_12.addWidget(self.pbDel, 1, 0, 1, 1)
        self.pbAdd = QtWidgets.QPushButton(self.tabCali)
        self.pbAdd.setMinimumSize(QtCore.QSize(0, 35))
        self.pbAdd.setObjectName("pbAdd")
        self.gridLayout_12.addWidget(self.pbAdd, 1, 1, 1, 1)
        self.tableCali = QtWidgets.QTableWidget(self.tabCali)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableCali.sizePolicy().hasHeightForWidth())
        self.tableCali.setSizePolicy(sizePolicy)
        self.tableCali.setAutoFillBackground(False)
        self.tableCali.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableCali.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableCali.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableCali.setObjectName("tableCali")
        self.tableCali.setColumnCount(2)
        self.tableCali.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableCali.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCali.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCali.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCali.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCali.setHorizontalHeaderItem(1, item)
        self.tableCali.horizontalHeader().setStretchLastSection(True)
        self.tableCali.verticalHeader().setStretchLastSection(True)
        self.gridLayout_12.addWidget(self.tableCali, 0, 0, 1, 2)
        self.pbCaliSubmit = QtWidgets.QPushButton(self.tabCali)
        self.pbCaliSubmit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.pbCaliSubmit.setFont(font)
        self.pbCaliSubmit.setObjectName("pbCaliSubmit")
        self.gridLayout_12.addWidget(self.pbCaliSubmit, 2, 0, 1, 2)
        self.pbCaliApply = QtWidgets.QPushButton(self.tabCali)
        self.pbCaliApply.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.pbCaliApply.setFont(font)
        self.pbCaliApply.setObjectName("pbCaliApply")
        self.gridLayout_12.addWidget(self.pbCaliApply, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tabCali, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.titleLE = QtWidgets.QLineEdit(self.tab_2)
        self.titleLE.setMinimumSize(QtCore.QSize(0, 30))
        self.titleLE.setObjectName("titleLE")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleLE)
        self.axisxLE = QtWidgets.QLineEdit(self.tab_2)
        self.axisxLE.setMinimumSize(QtCore.QSize(0, 30))
        self.axisxLE.setObjectName("axisxLE")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.axisxLE)
        self.axisyLE = QtWidgets.QLineEdit(self.tab_2)
        self.axisyLE.setMinimumSize(QtCore.QSize(0, 30))
        self.axisyLE.setObjectName("axisyLE")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.axisyLE)
        self.textCKB = QtWidgets.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.textCKB.setFont(font)
        self.textCKB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textCKB.setObjectName("textCKB")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textCKB)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.legendLE1 = QtWidgets.QLineEdit(self.tab_2)
        self.legendLE1.setMinimumSize(QtCore.QSize(0, 30))
        self.legendLE1.setObjectName("legendLE1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.legendLE1)
        self.legendLE2 = QtWidgets.QLineEdit(self.tab_2)
        self.legendLE2.setMinimumSize(QtCore.QSize(0, 30))
        self.legendLE2.setObjectName("legendLE2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.legendLE2)
        self.legendCKB = QtWidgets.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.legendCKB.setFont(font)
        self.legendCKB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.legendCKB.setObjectName("legendCKB")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.legendCKB)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tbStates = QtWidgets.QTextBrowser(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbStates.sizePolicy().hasHeightForWidth())
        self.tbStates.setSizePolicy(sizePolicy)
        self.tbStates.setObjectName("tbStates")
        self.gridLayout_3.addWidget(self.tbStates, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 2)
        self.plotTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.plotTabWidget.setObjectName("plotTabWidget")
        self.tabSpecView = QtWidgets.QWidget()
        self.tabSpecView.setObjectName("tabSpecView")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabSpecView)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.specPlot = PlotWidget(self.tabSpecView)
        self.specPlot.setObjectName("specPlot")
        self.gridLayout_4.addWidget(self.specPlot, 0, 0, 1, 1)
        self.plotTabWidget.addTab(self.tabSpecView, "")
        self.tabSnapView = QtWidgets.QWidget()
        self.tabSnapView.setObjectName("tabSnapView")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabSnapView)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.snapPlot = PlotWidget(self.tabSnapView)
        self.snapPlot.setObjectName("snapPlot")
        self.gridLayout_6.addWidget(self.snapPlot, 0, 0, 1, 1)
        self.plotTabWidget.addTab(self.tabSnapView, "")
        self.tabCaliView = QtWidgets.QWidget()
        self.tabCaliView.setObjectName("tabCaliView")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabCaliView)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.caliPlot = PlotWidget(self.tabCaliView)
        self.caliPlot.setObjectName("caliPlot")
        self.gridLayout_5.addWidget(self.caliPlot, 0, 0, 1, 1)
        self.plotTabWidget.addTab(self.tabCaliView, "")
        self.gridLayout.addWidget(self.plotTabWidget, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 18))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCom = QtWidgets.QMenu(self.menubar)
        self.menuCom.setObjectName("menuCom")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInput = QtWidgets.QAction(MainWindow)
        self.actionInput.setObjectName("actionInput")
        self.actionOutPut = QtWidgets.QAction(MainWindow)
        self.actionOutPut.setObjectName("actionOutPut")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionProject = QtWidgets.QAction(MainWindow)
        self.actionProject.setObjectName("actionProject")
        self.actionSerial = QtWidgets.QAction(MainWindow)
        self.actionSerial.setObjectName("actionSerial")
        self.actionGeneral = QtWidgets.QAction(MainWindow)
        self.actionGeneral.setObjectName("actionGeneral")
        self.actionAppearance = QtWidgets.QAction(MainWindow)
        self.actionAppearance.setObjectName("actionAppearance")
        self.actionDataFormat = QtWidgets.QAction(MainWindow)
        self.actionDataFormat.setObjectName("actionDataFormat")
        self.actionLocal = QtWidgets.QAction(MainWindow)
        self.actionLocal.setCheckable(True)
        self.actionLocal.setObjectName("actionLocal")
        self.actionSpec = QtWidgets.QAction(MainWindow)
        self.actionSpec.setCheckable(True)
        self.actionSpec.setObjectName("actionSpec")
        self.actionPeak = QtWidgets.QAction(MainWindow)
        self.actionPeak.setCheckable(True)
        self.actionPeak.setObjectName("actionPeak")
        self.menuFile.addAction(self.actionInput)
        self.menuCom.addAction(self.actionSerial)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionProject)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCom.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.plotTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Serial Closed"))
        self.groupBox.setTitle(_translate("MainWindow", "Transmission Controller"))
        self.pbStart.setText(_translate("MainWindow", "start"))
        self.pbStop.setText(_translate("MainWindow", "stop"))
        self.label_2.setText(_translate("MainWindow", "Time"))
        self.pbSnap.setText(_translate("MainWindow", "snap"))
        self.label_3.setText(_translate("MainWindow", "Work Mode"))
        self.modCB.setItemText(0, _translate("MainWindow", "Peak Mode"))
        self.modCB.setItemText(1, _translate("MainWindow", "Direct Mode"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Parameters Config"))
        self.packFlagPB.setText(_translate("MainWindow", "pack flag"))
        self.setTimePB.setText(_translate("MainWindow", "measure time"))
        self.packFlagLE.setText(_translate("MainWindow", "255"))
        self.fdMaxPB.setText(_translate("MainWindow", "find max"))
        self.setMaxEPB.setText(_translate("MainWindow", "max energy"))
        self.setRefNumPB.setText(_translate("MainWindow", "refresh num"))
        self.setChPB.setText(_translate("MainWindow", "set channels"))
        self.measTimeLE.setText(_translate("MainWindow", "1000"))
        self.chNumLE.setText(_translate("MainWindow", "1024"))
        self.maxELE.setText(_translate("MainWindow", "20000"))
        self.refNumLE.setText(_translate("MainWindow", "100"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.measure), _translate("MainWindow", "Measure"))
        self.dropFitType.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.dropFitType.setItemText(1, _translate("MainWindow", "Polynomial"))
        self.dropFitType.setItemText(2, _translate("MainWindow", "Exponential"))
        self.dropFitType.setItemText(3, _translate("MainWindow", "Power"))
        self.dropFitType.setItemText(4, _translate("MainWindow", "Interpolant"))
        self.pbFitCurve.setText(_translate("MainWindow", "FitCurve"))
        self.label_6.setText(_translate("MainWindow", "Method"))
        self.label_7.setText(_translate("MainWindow", "Eqaution"))
        self.caliEqCKB.setText(_translate("MainWindow", "apply to cali"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFit), _translate("MainWindow", "Fit Opts"))
        self.pbDel.setText(_translate("MainWindow", "Del (-)"))
        self.pbAdd.setText(_translate("MainWindow", "Add (+)"))
        item = self.tableCali.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableCali.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableCali.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableCali.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Peak"))
        item = self.tableCali.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Channel"))
        self.pbCaliSubmit.setText(_translate("MainWindow", "Submit"))
        self.pbCaliApply.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCali), _translate("MainWindow", "Cali Opts"))
        self.label_4.setText(_translate("MainWindow", "text"))
        self.titleLE.setPlaceholderText(_translate("MainWindow", "title"))
        self.axisxLE.setPlaceholderText(_translate("MainWindow", "x axis label"))
        self.axisyLE.setPlaceholderText(_translate("MainWindow", "y axis label"))
        self.textCKB.setText(_translate("MainWindow", "add"))
        self.label_5.setText(_translate("MainWindow", "legend"))
        self.legendLE1.setPlaceholderText(_translate("MainWindow", "fit data legend"))
        self.legendLE2.setPlaceholderText(_translate("MainWindow", "origion data legend"))
        self.legendCKB.setText(_translate("MainWindow", "add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Plot Opts"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Work State"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.tabSpecView), _translate("MainWindow", "View Spec"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.tabSnapView), _translate("MainWindow", "View Snap"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.tabCaliView), _translate("MainWindow", "View Cali"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCom.setTitle(_translate("MainWindow", "Com"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionInput.setText(_translate("MainWindow", "Input"))
        self.actionOutPut.setText(_translate("MainWindow", "OutPut"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionProject.setText(_translate("MainWindow", "Project"))
        self.actionSerial.setText(_translate("MainWindow", "Serial Port"))
        self.actionGeneral.setText(_translate("MainWindow", "General"))
        self.actionAppearance.setText(_translate("MainWindow", "Appearance"))
        self.actionDataFormat.setText(_translate("MainWindow", "DataFormat"))
        self.actionLocal.setText(_translate("MainWindow", "Local"))
        self.actionSpec.setText(_translate("MainWindow", "Spec"))
        self.actionPeak.setText(_translate("MainWindow", "Peak"))
from LedIndicatorWidget import LedIndicator
from pyqtgraph import PlotWidget
